[package]
name = "add-one"
version = "0.1.0"
authors = ["F3900699 Hamilton Geraldo Fantin <hamiltonfantin@bb.com.br>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rand = "0.5.5"