version: '3.7'
services:
  database:
    image: postgres:9.5
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
      POSTGRES_DB:       fornecedor
    volumes:
      - .docker/data/postgres:/var/lib/postgresql/data
