version: '3.7'
services:
  database:
    image: postgres:9.5
    ports:
      - 5432:5432
    volumes:
      - ./pg-init-scripts:/docker-entrypoint-initdb.d
#      - .docker/data/postgres:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=admin
      - POSTGRES_MULTIPLE_DATABASES=fornecedor,loja,transportador
    #      POSTGRES_DB:       fornecedor
