version: '3.7'
services:
  # database:
  #   image: postgres:9.5
  #   ports:
  #     - 5432:5432
  #   environment:
  #     POSTGRES_USER: admin
  #     POSTGRES_PASSWORD: 123456
  #     POSTGRES_DB:       elixir-teste
  #   volumes:
  #     - ../.data/postgres:/var/lib/postgresql/data
  # redis:
  #   image: redis:alpine
  #   ports:
  #     - 6379:6379
  rabbitmq:
    image: rabbitmq:management
    ports:
      - 5672:5672
      - 15672:15672
      - 25672:25672
    environment:
      - RABBITMQ_DEFAULT_USER=admin
      - RABBITMQ_DEFAULT_PASS=123456
